-- Educational templates, owned and editable through the existing Mentor CMS.
-- No personal strategies are inserted or overwritten. No statistical-performance claim.
WITH inserted AS (
INSERT INTO content_post(id,slug,status,created_by,content_type_id,template_fields,published_at,content_version)
SELECT uuid_generate_v4(),'intraday-trend-continuation','PUBLISHED',(SELECT id FROM users WHERE role='ADMIN' ORDER BY created_at LIMIT 1),c.id,'{"what": "Educational intraday structure template; not statistically validated", "when": "European or US liquid hours, using the exact instrument; H1/M15 context and M5/M1 execution", "riskModel": "Define structural invalidation before entry. Size only within the account risk limit. Do not widen the stop.", "entryModel": "Directional structure and a controlled pullback to a relevant area.", "filters": ["Identify higher highs/lows or lower highs/lows on H1/M15.", "Wait for a pullback into prior structure or a verified session level.", "Require M5/M1 rejection and a confirmed continuation structure break."], "checklist": ["Identify higher highs/lows or lower highs/lows on H1/M15.", "Wait for a pullback into prior structure or a verified session level.", "Require M5/M1 rejection and a confirmed continuation structure break."], "entryConditionsRich": "<h3>Context \u00b7 H1 / M15</h3><p>Directional structure and a controlled pullback to a relevant area.</p><h3>Execution \u00b7 M5 / M1</h3><ul><li>Identify higher highs/lows or lower highs/lows on H1/M15.</li><li>Wait for a pullback into prior structure or a verified session level.</li><li>Require M5/M1 rejection and a confirmed continuation structure break.</li></ul><h3>Instruments and sessions</h3><p>DAX, Nasdaq-100, ES; European / US liquid hours, using the exact traded instrument.</p><h3>Example</h3><p>An uptrend retraces into prior resistance now acting as support. Wait for a higher low and a break of local resistance.</p><p>Educational template v1. Not statistically validated.</p>", "invalidation": "Stop beyond the pullback structure; continuation invalidates when price accepts beyond it.", "targets": "First opposing structure; reduce exposure according to the plan, without widening the stop.", "failureModes": "No clear direction, entry far from invalidation, or imminent high-impact release."}'::jsonb,CURRENT_TIMESTAMP,1
FROM content_type c WHERE c.key='STRATEGY' AND EXISTS(SELECT 1 FROM users WHERE role='ADMIN') ON CONFLICT(slug) DO NOTHING RETURNING id
)
INSERT INTO content_post_translation(content_post_id,locale,title,summary,body_markdown)
SELECT inserted.id,locale,'Trend continuation','Directional structure and a controlled pullback to a relevant area.','An uptrend retraces into prior resistance now acting as support. Wait for a higher low and a break of local resistance.' FROM inserted CROSS JOIN (VALUES ('en'),('ro')) languages(locale);
WITH inserted AS (
INSERT INTO content_post(id,slug,status,created_by,content_type_id,template_fields,published_at,content_version)
SELECT uuid_generate_v4(),'intraday-reversal','PUBLISHED',(SELECT id FROM users WHERE role='ADMIN' ORDER BY created_at LIMIT 1),c.id,'{"what": "Educational intraday structure template; not statistically validated", "when": "European or US liquid hours, using the exact instrument; H1/M15 context and M5/M1 execution", "riskModel": "Define structural invalidation before entry. Size only within the account risk limit. Do not widen the stop.", "entryModel": "A significant area, failed continuation and confirmed change of structure.", "filters": ["Identify a meaningful previous high/low or session extreme.", "Observe a failed breakout or liquidity sweep and rejection.", "Wait for a confirmed structure change and a retest before considering entry."], "checklist": ["Identify a meaningful previous high/low or session extreme.", "Observe a failed breakout or liquidity sweep and rejection.", "Wait for a confirmed structure change and a retest before considering entry."], "entryConditionsRich": "<h3>Context \u00b7 H1 / M15</h3><p>A significant area, failed continuation and confirmed change of structure.</p><h3>Execution \u00b7 M5 / M1</h3><ul><li>Identify a meaningful previous high/low or session extreme.</li><li>Observe a failed breakout or liquidity sweep and rejection.</li><li>Wait for a confirmed structure change and a retest before considering entry.</li></ul><h3>Instruments and sessions</h3><p>DAX, Nasdaq-100, ES; European / US liquid hours, using the exact traded instrument.</p><h3>Example</h3><p>Price sweeps a previous high, returns below it, breaks the last higher low and rejects a retest.</p><p>Educational template v1. Not statistically validated.</p>", "invalidation": "Stop beyond the rejected extreme; acceptance beyond the extreme invalidates the reversal.", "targets": "Next internal structure, then opposing liquidity if the structure supports continuation.", "failureModes": "An extreme alone is insufficient; avoid fading strong unbroken momentum."}'::jsonb,CURRENT_TIMESTAMP,1
FROM content_type c WHERE c.key='STRATEGY' AND EXISTS(SELECT 1 FROM users WHERE role='ADMIN') ON CONFLICT(slug) DO NOTHING RETURNING id
)
INSERT INTO content_post_translation(content_post_id,locale,title,summary,body_markdown)
SELECT inserted.id,locale,'Reversal','A significant area, failed continuation and confirmed change of structure.','Price sweeps a previous high, returns below it, breaks the last higher low and rejects a retest.' FROM inserted CROSS JOIN (VALUES ('en'),('ro')) languages(locale);
WITH inserted AS (
INSERT INTO content_post(id,slug,status,created_by,content_type_id,template_fields,published_at,content_version)
SELECT uuid_generate_v4(),'intraday-range','PUBLISHED',(SELECT id FROM users WHERE role='ADMIN' ORDER BY created_at LIMIT 1),c.id,'{"what": "Educational intraday structure template; not statistically validated", "when": "European or US liquid hours, using the exact instrument; H1/M15 context and M5/M1 execution", "riskModel": "Define structural invalidation before entry. Size only within the account risk limit. Do not widen the stop.", "entryModel": "Identifiable boundaries with repeated rejection and balanced price action.", "filters": ["Mark two boundaries supported by repeated reactions.", "Work near an extreme; avoid the middle without a separate setup.", "Require rejection back inside and a defined structural invalidation."], "checklist": ["Mark two boundaries supported by repeated reactions.", "Work near an extreme; avoid the middle without a separate setup.", "Require rejection back inside and a defined structural invalidation."], "entryConditionsRich": "<h3>Context \u00b7 H1 / M15</h3><p>Identifiable boundaries with repeated rejection and balanced price action.</p><h3>Execution \u00b7 M5 / M1</h3><ul><li>Mark two boundaries supported by repeated reactions.</li><li>Work near an extreme; avoid the middle without a separate setup.</li><li>Require rejection back inside and a defined structural invalidation.</li></ul><h3>Instruments and sessions</h3><p>DAX, Nasdaq-100, ES; European / US liquid hours, using the exact traded instrument.</p><h3>Example</h3><p>A third test of support fails to sustain below the range. A reclaim allows a conditional plan toward the midpoint.</p><p>Educational template v1. Not statistically validated.</p>", "invalidation": "Stop outside the rejected boundary; sustained acceptance outside ends the range thesis.", "targets": "First the midpoint if risk/reward supports it, then the opposite boundary.", "failureModes": "Unclear boundaries, expansion after news, or insufficient room to the midpoint."}'::jsonb,CURRENT_TIMESTAMP,1
FROM content_type c WHERE c.key='STRATEGY' AND EXISTS(SELECT 1 FROM users WHERE role='ADMIN') ON CONFLICT(slug) DO NOTHING RETURNING id
)
INSERT INTO content_post_translation(content_post_id,locale,title,summary,body_markdown)
SELECT inserted.id,locale,'Range','Identifiable boundaries with repeated rejection and balanced price action.','A third test of support fails to sustain below the range. A reclaim allows a conditional plan toward the midpoint.' FROM inserted CROSS JOIN (VALUES ('en'),('ro')) languages(locale);

CREATE TABLE mentor_strategy_adoptions (
 user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 content_id UUID NOT NULL REFERENCES content_post(id),
 strategy_id UUID NOT NULL REFERENCES user_strategies(id),
 PRIMARY KEY(user_id,content_id)
);
