ALTER TABLE backtesting_trades ALTER COLUMN pnl_r DROP NOT NULL;
ALTER TABLE backtesting_trades ADD COLUMN exit_date DATE;
ALTER TABLE backtesting_trades ADD COLUMN exit_time TIME;
ALTER TABLE backtesting_trades ADD COLUMN entry_price NUMERIC(24,8);
ALTER TABLE backtesting_trades ADD COLUMN exit_price NUMERIC(24,8);
ALTER TABLE backtesting_trades ADD COLUMN quantity NUMERIC(24,8);
ALTER TABLE backtesting_trades ADD COLUMN position_value NUMERIC(24,8);
ALTER TABLE backtesting_trades ADD COLUMN net_pnl NUMERIC(24,8);
ALTER TABLE backtesting_trades ADD COLUMN currency VARCHAR(3);
ALTER TABLE backtesting_trades ADD COLUMN return_percent NUMERIC(24,8);
ALTER TABLE backtesting_trades ADD COLUMN commission NUMERIC(24,8);
ALTER TABLE backtesting_trades ADD COLUMN favorable_excursion NUMERIC(24,8);
ALTER TABLE backtesting_trades ADD COLUMN adverse_excursion NUMERIC(24,8);
ALTER TABLE backtesting_trades ADD COLUMN favorable_excursion_percent NUMERIC(24,8);
ALTER TABLE backtesting_trades ADD COLUMN adverse_excursion_percent NUMERIC(24,8);
ALTER TABLE backtesting_trades ADD COLUMN reported_cumulative_pnl NUMERIC(24,8);
ALTER TABLE backtesting_trades ADD COLUMN reported_cumulative_percent NUMERIC(24,8);
ALTER TABLE backtesting_trades ADD COLUMN duration_bars INTEGER;
ALTER TABLE backtesting_trades ADD COLUMN entry_signal VARCHAR(255);
ALTER TABLE backtesting_trades ADD COLUMN exit_signal VARCHAR(255);
ALTER TABLE backtesting_trades ADD COLUMN import_format VARCHAR(64);
ALTER TABLE backtesting_trades ADD COLUMN import_file_name VARCHAR(255);
ALTER TABLE backtesting_trades ADD COLUMN import_trade_number VARCHAR(64);
ALTER TABLE backtesting_trades ADD COLUMN import_fingerprint VARCHAR(64);
ALTER TABLE backtesting_trades ADD COLUMN source_timezone VARCHAR(64);
CREATE UNIQUE INDEX ux_backtesting_replay_fingerprint ON backtesting_trades (workspace_id, import_fingerprint) WHERE import_fingerprint IS NOT NULL;
