import { useCallback, useEffect, useRef, useState } from 'react'
import { Alert, Box, Button, Card, CardContent, Checkbox, FormControlLabel, MenuItem, Stack, TextField, Typography } from '@mui/material'
import { useI18n } from '../../i18n'
import { useAuth } from '../../auth/AuthContext'
import { apiGet, apiPost, apiPut } from '../../api/client'
import { BriefingDocument, Translation, Slot, slots, editorialDate, emptyDocument, emptyTranslation, parseImport } from '../../features/briefings/model'
import { EditorialDocument } from '../../features/briefings/EditorialView'

type Draft={id:string;version:number;document:BriefingDocument}
type DayRow={id:string;slot:Slot;version:number;published_draft_version:number|null;withdrawn:boolean;revision:number|null;reference_time:string;published_at:string;updated_by:string}
const fields={facts:['id','time','topic','statement','source','sourceUrl','availableAt','availabilityNotEstablished','relatedFactId','relationship'],news:['headline','publishedAt','source','sourceUrl','summary','relevance'],events:['id','scheduledAt','timezone','region','name','source','sourceUrl','actual','forecast','previous','unit','explanation','status'],macro:['instrument','type','value','unit','observedAt','source','sourceUrl','referenceValue','referenceAt','availability'],scenarios:['market','instrument','source','type','contract','context','bias','main','alternative','invalidation','risks','limitations']} as const
const choices:Record<string,string[]>={relationship:['','UPDATE','CORRECTION','CONTINUATION'],status:['UPCOMING','RELEASED','RESCHEDULED','CANCELLED'],market:['DAX','NASDAQ_100','ES'],bias:['neutral','bullish','bearish','mixed']}
const timeFields=new Set(['time','publishedAt','scheduledAt','observedAt','referenceAt','availableAt'])
function newEntry(section:keyof typeof fields): Record<string,unknown> {
 const result:Record<string,unknown>={};fields[section].forEach(f=>result[f]=timeFields.has(f)?(f==='time'||f==='referenceAt'||f==='availableAt'?null:new Date().toISOString()):f==='value'||f==='referenceValue'?null:f==='relationship'||f==='relatedFactId'?null:choices[f]?.filter(Boolean)[0] || '')
 if(section==='events')result.timezone='Europe/Bucharest'
 return result
}
function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
export default function AdminSessionBriefingsPage(){
 const {t,language}=useI18n();const {user}=useAuth()
 const [date,setDate]=useState(editorialDate());const [rows,setRows]=useState<DayRow[]>([]);const [draft,setDraft]=useState<Draft>();const latest=useRef<Draft>();latest.current=draft
 const [locale,setLocale]=useState<'en'|'ro'>(language);const [saveState,setSaveState]=useState('Saved');const [error,setError]=useState('');const [paste,setPaste]=useState('');const [imported,setImported]=useState<BriefingDocument>();const [preview,setPreview]=useState<BriefingDocument>();const [reviewed,setReviewed]=useState(false);const [history,setHistory]=useState<unknown>();const [recovery,setRecovery]=useState<BriefingDocument>();const [busy,setBusy]=useState(false)
 const saving=useRef(false);const sequence=useRef(0);const publishKey=useRef(crypto.randomUUID())
 const storageKey=(id:string)=>`editorial.draft.${user?.id}.${id}`
 const loadDay=useCallback(async()=>{try{setRows(await apiGet<DayRow[]>(`/admin/session-briefings?date=${date}`))}catch(e){setError(String(e))}},[date])
 useEffect(()=>{void loadDay()},[loadDay])
 async function open(id:string){if(saving.current)return;try{const next=await apiGet<Draft>(`/admin/session-briefings/${id}`);setDraft(next);latest.current=next;setLocale(next.document.translations[language]?language:next.document.contentLanguage);setSaveState('Saved');setPreview(undefined);setHistory(undefined);setError('');const raw=localStorage.getItem(storageKey(id));setRecovery(raw?JSON.parse(raw):undefined)}catch(e){setError(String(e))}}
 function edit(document:BriefingDocument){if(!latest.current)return;sequence.current++;const next={...latest.current,document};latest.current=next;setDraft(next);setPreview(undefined);setReviewed(false);setSaveState('Pending');try{localStorage.setItem(storageKey(next.id),JSON.stringify(document))}catch{setSaveState('Failed');setError(t('editorial.localRecoveryFailed'))}}
 async function save():Promise<Draft|undefined>{
  const current=latest.current;if(!current || saving.current)return
  saving.current=true;setSaveState('Saving');const seq=sequence.current
  try{const result=await apiPut<Draft>(`/admin/session-briefings/${current.id}`,{version:current.version,document:current.document});
   const next=sequence.current===seq?result:{...result,document:latest.current!.document};latest.current=next;setDraft(next);setSaveState(sequence.current===seq?'Saved':'Pending');
   if(sequence.current===seq)localStorage.removeItem(storageKey(current.id));void loadDay();return next
  }catch(e){setSaveState('Failed');setError(String(e));return undefined}finally{saving.current=false}
 }
 const saveAction=useRef(save);saveAction.current=save
 useEffect(()=>{if(saveState!=='Pending')return;const timer=setTimeout(()=>void saveAction.current(),900);return()=>clearTimeout(timer)},[draft,saveState])
 async function create(slot:Slot){setBusy(true);try{const result=await apiPost<Draft>('/admin/session-briefings',{version:0,document:emptyDocument(date,slot,language)});setDraft(result);latest.current=result;setLocale(language);setPreview(undefined);setHistory(undefined);setRecovery(undefined);setError('');setSaveState('Saved');void loadDay()}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function showPreview(){setBusy(true);setError('');try{const current=saveState==='Saved'?latest.current:await save();if(!current)return;const seq=sequence.current;const valid=await apiPost<BriefingDocument>('/admin/session-briefings/preview',current.document);if(seq!==sequence.current || latest.current?.version!==current.version)return;setPreview(valid);setReviewed(false);publishKey.current=crypto.randomUUID()}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function publish(){if(!draft||!preview||!reviewed||busy)return;setBusy(true);setError('');try{await apiPost(`/admin/session-briefings/${draft.id}/publish`,{version:draft.version,requestId:publishKey.current});setPreview(undefined);setReviewed(false);await loadDay()}catch(e){setError(String(e))}finally{setBusy(false)}}
 const document=draft?.document;const content=document?.translations[locale]
 function changeContent(patch:Partial<Translation>){if(document&&content)edit({...document,translations:{...document.translations,[locale]:{...content,...patch}}})}
 const locked=busy||saveState==='Saving'||saveState==='Pending'
 return <Stack spacing={2} sx={{minWidth:0,overflowWrap:'anywhere'}}>
 <Typography component="h1" variant="h5">{t('editorial.adminTitle')}</Typography><Typography>Europe/Bucharest · {t('editorial.adminTimezone')}</Typography>
 <TextField type="date" label={t('editorial.editorialDate')} value={date} disabled={locked} onChange={e=>{if(e.target.value){setDate(e.target.value);setDraft(undefined);latest.current=undefined;setPreview(undefined);setHistory(undefined);setRecovery(undefined);setImported(undefined)}}} InputLabelProps={{shrink:true}}/>
 {error && <Alert severity="error" sx={{whiteSpace:'pre-wrap'}}>{error}</Alert>}
 <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(3,minmax(0,1fr))'},gap:1}}>{slots.map(slot=>{const row=rows.find(r=>r.slot===slot);const status=!row?'Missing':row.withdrawn?'Withdrawn':row.published_draft_version!==row.version?'Draft':(row.revision || 0)>1?'Updated':'Published';return <Card key={slot}><CardContent><Stack spacing={1}><Typography component="h2" variant="h6">{t(`editorial.${slot}`)}</Typography><Typography>{t(`editorial.${status}`)} {row?.revision?`· r${row.revision}`:''}</Typography><Typography variant="caption">{t('editorial.referenceTime')}: {row?.reference_time || '—'}<br/>{t('editorial.publishedAt')}: {row?.published_at || '—'}<br/>{t('editorial.editor')}: {row?.updated_by || '—'}</Typography><Button disabled={locked} onClick={()=>row?void open(row.id):void create(slot)}>{t(row?'editorial.editDraft':'editorial.createDraft')}</Button><Button onClick={()=>download(`briefing-${slot}.json`,JSON.stringify(emptyDocument(date,slot,language),null,2))}>{t('editorial.downloadTemplate')}</Button></Stack></CardContent></Card>})}</Box>
 {draft && document && <><Stack direction="row" flexWrap="wrap" useFlexGap spacing={1}><Typography role="status">{t(`editorial.${saveState}`)} · v{draft.version}</Typography><Button disabled={busy||saving.current} onClick={()=>void save()}>{t('editorial.save')}</Button><Button disabled={locked} onClick={()=>void open(draft.id)}>{t('editorial.reload')}</Button><Button disabled={locked} onClick={async()=>{try{setHistory(await apiGet(`/admin/session-briefings/${draft.id}/history`))}catch(e){setError(String(e))}}}>{t('editorial.history')}</Button><Button disabled={locked} color="warning" onClick={async()=>{setBusy(true);try{await apiPost(`/admin/session-briefings/${draft.id}/withdraw`,{version:draft.version,requestId:crypto.randomUUID()});await open(draft.id);await loadDay()}catch(e){setError(String(e))}finally{setBusy(false)}}}>{t('editorial.withdraw')}</Button></Stack>
 {recovery && <Alert severity="warning">{t('editorial.recover')}<Button onClick={()=>{edit(recovery);setRecovery(undefined)}}>{t('editorial.restore')}</Button><Button onClick={()=>download('retained-draft.json',JSON.stringify(recovery,null,2))}>{t('editorial.download')}</Button></Alert>}
 {saveState==='Failed' && <Alert severity="warning">{t('editorial.conflict')}<Button onClick={()=>download('unsaved-briefing.json',JSON.stringify(document,null,2))}>{t('editorial.download')}</Button></Alert>}
 <Typography component="h2" variant="h6">{document.editorialDate} · {t(`editorial.${document.slot}`)}</Typography>
 <Box component="details"><Box component="summary" sx={{py:1,cursor:'pointer'}}>{t('editorial.paste')}</Box><Stack spacing={1}><TextField multiline minRows={8} label={t('editorial.paste')} value={paste} onChange={e=>{setPaste(e.target.value);setImported(undefined)}}/><Button onClick={()=>{try{setImported(parseImport(paste));setError('')}catch(e){setError(String(e))}}}>{t('editorial.validateImport')}</Button>{imported && <><EditorialDocument document={imported}/><Button onClick={()=>{if(imported.editorialDate!==document.editorialDate||imported.slot!==document.slot){setError(t('editorial.identityMismatch'));return}edit(imported);setImported(undefined)}}>{t('editorial.useImport')}</Button></>}</Stack></Box>
 <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(2,minmax(0,1fr))'},gap:1}}>
 {(['coverageStart','coverageEnd','referenceTime','author','aiDisclosure'] as const).map(field=><TextField key={field} label={t(`editorial.${field}`)} value={document[field] || ''} onChange={e=>edit({...document,[field]:e.target.value})} helperText={field.includes('Time')||field.startsWith('coverage')?'ISO 8601 · UTC / offset':undefined}/>)}
 <TextField select label={t('editorial.coverage')} value={document.coverage} onChange={e=>edit({...document,coverage:e.target.value as BriefingDocument['coverage']})}>{['ONGOING','COMPLETE'].map(v=><MenuItem key={v} value={v}>{t(`editorial.${v}`)}</MenuItem>)}</TextField>
 <TextField select label={t('editorial.contentLanguage')} value={document.contentLanguage} onChange={e=>edit({...document,contentLanguage:e.target.value as 'en'|'ro'})}>{['en','ro'].map(v=><MenuItem key={v} value={v}>{v.toUpperCase()}</MenuItem>)}</TextField>
 </Box>
 <Stack direction="row" spacing={1}>{(['en','ro'] as const).map(l=><Button variant={locale===l?'contained':'outlined'} key={l} onClick={()=>setLocale(l)}>{l.toUpperCase()} · {document.translations[l]?t('editorial.present'):t('editorial.Missing')}</Button>)}</Stack>
 {!content?<Button onClick={()=>edit({...document,translations:{...document.translations,[locale]:emptyTranslation()}})}>{t('editorial.addTranslation')}</Button>:<>
 <TextField label={t('editorial.title')} value={content.title} onChange={e=>changeContent({title:e.target.value})}/>
 <TextField multiline minRows={3} label={t('editorial.summary')} helperText={t('editorial.summaryHelp')} value={content.summary.join('\n')} onChange={e=>changeContent({summary:e.target.value.split('\n')})}/>
 {(Object.keys(fields) as (keyof typeof fields)[]).map(section=><Box component="details" key={section}><Box component="summary" sx={{py:1,cursor:'pointer',fontWeight:600}}>{t(`editorial.${section}`)} ({content[section].length})</Box><Stack spacing={2}>{content[section].map((entry,index)=><Card variant="outlined" key={index}><CardContent><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(2,minmax(0,1fr))'},gap:1}}>{fields[section].map(field=>{const value=(entry as unknown as Record<string,unknown>)[field];return <TextField key={field} label={t(`editorial.${field}`)} value={value??''} select={Boolean(choices[field])} multiline={!choices[field]&&!timeFields.has(field)} minRows={1} helperText={timeFields.has(field)?'ISO 8601 · UTC / offset':undefined} onChange={e=>{const arr=[...content[section]];const raw=e.target.value;const next=field==='value'||field==='referenceValue'?(raw===''?null:Number(raw)):raw===''&&(timeFields.has(field)||field==='relationship'||field==='relatedFactId')?null:raw;arr[index]={...entry,[field]:next} as never;changeContent({[section]:arr})}}>{choices[field]?.map(v=><MenuItem key={v} value={v}>{v||'—'}</MenuItem>)}</TextField>})}</Box><Button color="warning" onClick={()=>changeContent({[section]:content[section].filter((_,i)=>i!==index)})}>{t('editorial.remove')}</Button></CardContent></Card>)}<Button onClick={()=>changeContent({[section]:[...content[section],newEntry(section)]})}>{t('editorial.add')}</Button></Stack></Box>)}
 <TextField multiline minRows={3} label={t('editorial.sourcesAndLimitations')} value={content.sourcesAndLimitations} onChange={e=>changeContent({sourcesAndLimitations:e.target.value})}/>
 </>}
 <Button disabled={busy||saveState==='Saving'} variant="outlined" onClick={()=>void showPreview()}>{t('editorial.preview')}</Button>
 {preview && <Card><CardContent><Stack spacing={2}><Typography variant="h6">{t('editorial.preview')}</Typography><EditorialDocument document={preview}/><FormControlLabel control={<Checkbox checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>} label={`${t('editorial.reviewTranslations')}: ${Object.keys(preview.translations).join(', ').toUpperCase()}`}/><Button variant="contained" disabled={!reviewed||busy||saveState!=='Saved'} onClick={()=>void publish()}>{t('editorial.publish')}</Button></Stack></CardContent></Card>}
 {history!==undefined && <Box component="details" open><Box component="summary">{t('editorial.history')}</Box><Box component="pre" sx={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',fontSize:12}}>{JSON.stringify(history,null,2)}</Box></Box>}
 </>}
 </Stack>
}
