package com.tradevault.dto.trade;

import com.fasterxml.jackson.databind.JsonNode;
import com.tradevault.domain.enums.Direction;
import com.tradevault.domain.enums.Market;
import com.tradevault.domain.enums.TradeGrade;
import com.tradevault.domain.enums.TradeSession;
import com.tradevault.domain.enums.TradeStatus;
import lombok.Builder;
import lombok.Data;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Set;
import java.util.UUID;

@Data
@Builder
public class TradeResponse {
    private UUID id;
    private String symbol;
    private Market market;
    private Direction direction;
    private TradeStatus status;
    private OffsetDateTime openedAt;
    private OffsetDateTime closedAt;
    private BigDecimal quantity;
    private BigDecimal entryPrice;
    private BigDecimal exitPrice;
    private BigDecimal stopLossPrice;
    private BigDecimal takeProfitPrice;
    private BigDecimal fees;
    private BigDecimal feesProfileCurrency;
    private BigDecimal commission;
    private BigDecimal slippage;
    private BigDecimal pnlNet;
    private BigDecimal pnlGross;
    private BigDecimal pnlProfileCurrency;
    private String tradeCurrency;
    private String profileCurrency;
    private BigDecimal fxRateTradeToProfile;
    private OffsetDateTime fxRateTimestamp;
    private String fxRateSource;
    private BigDecimal pnlPercent;
    private BigDecimal rMultiple;
    private BigDecimal riskAmount;
    private BigDecimal riskPercent;
    private BigDecimal capitalUsed;
    private String timeframe;
    private String setup;
    private String strategyName;
    private String strategyTag;
    private String catalystTag;
    private UUID strategyId;
    private UUID strategyVersionId;
    private UUID contextSnapshotId;
    private TradeGrade setupGrade;
    private Set<String> ruleBreaks;
    private TradeSession session;
    private UUID sessionId;
    private UUID setupId;
    private UUID sweepLevelId;
    private UUID sweepPoolId;
    private UUID entryLevelId;
    private UUID slLevelId;
    private UUID tpLevelId;
    private JsonNode narrativeSnapshotJson;
    private Boolean sweepConfirmed;
    private Boolean displacementConfirmed;
    private Boolean mssConfirmed;
    private BigDecimal sweepDepthPoints;
    private BigDecimal displacementSizePoints;
    private Integer timeSweepToEntrySeconds;
    private BigDecimal mfePoints;
    private BigDecimal maePoints;
    private Boolean levelExpectationMet;
    private String levelExpectation;
    private String feeling;
    private Set<UUID> linkedContentIds;
    private Set<UUID> linkedPlanIds;
    private String notes;
    private UUID latestTradeNoteId;
    private String latestTradeNotePreview;
    private OffsetDateTime latestTradeNoteUpdatedAt;
    private String initialNotes;
    private String entryJournalText;
    private String entryInvalidation;
    private Set<UUID> entryScreenshotAssetIds;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
    private String accountId;
    private UUID accountRefId;
    private BigDecimal contractMultiplier;
    private Set<String> tags;
}
